#!/usr/bin/env bash
# install nginx

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	sudo apt-get install nginx -y

echo -e "\nSetting up the Hello World! page.\n"

# starting nginx service
sudo service nginx start

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Gives the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp


# create a basic HTML page (new index)
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html


# restart nginx
sudo service nginx restart

# check the result
echo -e "\nCompleted.\n"
