#!/usr/bin/env bash
# install nginx
# Configure your Nginx server so that /redirect_me is
# redirecting to another page.

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && sudo apt-get install nginx -y

echo -e "\nSetting up the Hello World! page.\n"

# starting nginx service
sudo service nginx start

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Gives the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp


# create a basic HTML page (new index)
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# setting up the /redirect_me to a youtube video
sudo sed -i '24i\      rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

#set up of the 404 page
echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '25i\      error_page 404 /error_404.html;' /etc/nginx/sites-available/default
# restart nginx
sudo service nginx restart

# check the result
echo -e "\nCompleted.\n"
