#!/usr/bin/env bash
# configures a brand new Ubuntu machine to the requirements;
# configure web-02 to be identical to web-01
# add a custom Nginx response header to track which web
# server is answering our HTTP requests, to understand and
# track the way a load balancer works.
# Configure Nginx so that its HTTP response contains a
# custom header (on web-01 and web-02
# The name of the custom HTTP header must be X-Served-By
# The value of the custom HTTP header must be the hostname
# of the server Nginx is running on


