#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

echo -e "Installing and Configuring HAProxy on server....\n"

function install() {
        command -v "$1" &> /dev/null

        # disabling shellcheck=SC2181
        if [ $? -ne 0 ]; then
                echo -e "Installing: $1\n"
                sudo apt-get update -y -qq && sudo apt-get install -y "$1" -qq
                echo -e "\n"
        else
                echo -e "${1} is already installed in server.\n"
        fi
}

# Install HAProxy
install haproxy

echo -e "configuring........\n"

# backup default server config file
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

haproxy_config="
        defaults
          mode http
          timeout client 15s
          timeout connect 10s
          timeout server 15s
          timeout http-request 10s

        frontend clickviral-tech-frontend
            bind *:80
            default_backend clickviral-tech-backend

        backend clickviral-tech-backend
            balance roundrobin
            server 430728-web-01 54.167.187.121:80 check
            server 430728-web-02 100.25.3.235:80 check
        "


# shellcheck disable=SC2154
echo "$haproxy_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

if [ "$(pgrep -c haproxy)" -le 0 ]; then
	sudo service haproxy start
else
	sudo service haproxy restart
fi
