#!/usr/bin/env bash
# transfer file from client to server
# check if number of parameter is less than 4
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# assigned parameter to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

# use scp to transfer the file to the user home directory on the server
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username"@"$server_ip":~/

# check if scp command was successful
if [ "$?" -eq 0 ]; then
    echo "File successfully transferred to $username@$server_ip:~/"
else
    echo "Error: File transfer failed"
fi
