#!/usr/bin/env bash
# script that displays to_infinity_and_beyond
# indefinitely with a sleep 2 in between each iteraction.
# displays "I am invincible!!!" inbetween each iteration.

while true; do
	echo "To infinity and beyond"
	sleep 2
	trp 'echo "I am invincible!!!"' SIGTERM
done
