#!/usr/bin/env bash
# script that indefinitely write
# "I am alive" to the file /tmp/my_process.
# and pauses two seconds inbetween each message

while true; do
	echo "I am alive" >> /tmp/my_process
	sleep 2
done
