#!/usr/bin/env bash
# Configure a UFW (uncomplicated fire wall) to
# block all incoming  traffics except for tcp
# ports 22, 80 and 443.

sudo apt install ufw
sudo ufw deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable
sudo ufw status verbose
