#!/usr/bin/env bash
# script that configures an Ubuntu server
# with the requirements:
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8
# the checker is running on Docker, 
#+ so make sure to read this

cp /etc/hosts -/hosts.new
echo "127.0.0.2      localhost" > -/hosts.new
echo "8.8.8.8        facebook.com" >> -/hosts.new
cp -f -/hosts.new /etc/hosts
